import { Dish } from './models/Dish';

export const dishes: Dish[] = [
  {
    id: 1,
    name: 'Pierogi',
    description:
      'Undeniable, pierogi is the most popular Polish food. Pierogi is already plural in Polish (pieróg is singular), but in the US people love to call it pierogis which makes no sense. They are thinly rolled-out dough filled with a variety of fillings, savory or sweet. They could be served as an appetizer, main dish or dessert.',
    image: 'https://annaeverywhere.com/wp-content/uploads/2019/08/pierogi.jpg',
    steps: [
      'To make the dough: Mix together the flour and salt. Add the egg to the flour and combine. The dough will be quite clumpy at this stage.',
      'Work in the sour cream and soft butter until the dough comes together in a slightly rough, slightly sticky ball.',
      'Using just your fingertips, knead and fold the dough without adding additional flour until the dough becomes less sticky but still quite moist.',
      'Wrap the dough well in plastic wrap and refrigerate for 30 to 60 minutes, or up to 48 hours.',
      'To make the filling: Combine the warm mashed potato and cheese. Stir and mash until the cheese is melted and the filling is cool to the touch. Taste and adjust the seasonings with salt and pepper.',
      'To fill the pierogi: Roll half the dough 1/8" thick. Use a 2" round cutter to cut circles of dough. Repeat with the other half of the dough. Save the scraps; these can be snipped into small pieces and added to simmering soups.',
      'Place 1 1/2 teaspoons of filling on each round of dough. Gently fold the dough over, forming a pocket around the filling. Pinch the edges of the pierogi to seal, then seal again with the tines of a fork.',
      'At this point the pierogi can be frozen for up to 4 weeks, or refrigerated overnight, or cooked in a large stockpot of boiling salted water. Only cook about 10 pierogi at a time, so that they have room to float without sticking. When the pierogi float, they are done. The time will vary depending on if they are fresh or frozen.',
      'Sauté the shallots or onion in the butter in a large skillet until the onion begins to brown. Add the drained pierogi and cook until browned and crisped. Serve hot with additional sour cream, applesauce, or other condiments.',
    ],
    ingredients: [
      {
        section: 'Dough',
        items: [
          '2 cups (240g) King Arthur Unbleached All-Purpose Flour',
          '1/2 teaspoon salt',
          '1 large egg',
          '1/2 cup (113g) sour cream',
          '4 tablespoons (57g) butter, room temperature',
        ],
      },
      {
        section: 'Filling',
        items: [
          '1 cup (227g) mashed potatoes, warm',
          '1 cup (113g) sharp cheddar cheese, shredded',
        ],
      },
      {
        section: 'To finish',
        items: [
          '4 tablespoons (57g) butter, cold',
          '2 large (156g) shallots, diced; or one medium (156g) onion, sliced',
        ],
      },
    ],
  },
  {
    id: 2,
    name: 'Golabki ',
    description:
      'Polish golabki (translating directly it means ‘little pigeons’) is cooked minced meat, often with onions and mushrooms, wrapped up in a leaf of white cabbage and stewed. It’s one of the dishes that was surely brought to the US by Polish immigrants.',
    image: 'https://annaeverywhere.com/wp-content/uploads/2019/08/golabki.jpg',
    steps: [
      'Bring a large pot of lightly salted water to a boil. Place cabbage head into water, cover pot, and cook until cabbage leaves are slightly softened enough to remove from head, 3 minutes. Remove cabbage from pot and let cabbage sit until leaves are cool enough to handle, about 10 minutes.',
      'Remove 18 whole leaves from the cabbage head, cutting out any thick tough center ribs. Set whole leaves aside. Chop the remainder of the cabbage head and spread it in the bottom of a casserole dish.',
      'Melt butter in a large skillet over medium-high heat. Cook and stir onion in hot butter until tender, 5 to 10 minutes. Cool.',
      'Stir onion, beef, pork, rice, garlic, 1 teaspoon salt, and 1/4 teaspoon pepper together in a large bowl.',
      'Preheat oven to 350 degrees F (175 degrees C).',
      'Place about 1/2 cup beef mixture on a cabbage leaf. Roll cabbage around beef mixture, tucking in sides to create an envelope around the meat. Repeat with remaining leaves and meat mixture. Place cabbage rolls in a layer atop the chopped cabbage in the casserole dish; season rolls with salt and black pepper.',
      'Whisk tomato soup, tomato juice, and ketchup together in a bowl. Pour tomato soup mixture over cabbage rolls and cover dish wish aluminum foil',
      'Bake in the preheated oven until cabbage is tender and meat is cooked through, about 1 hour.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '1 head cabbage, cored',
          '2 tablespoons butter',
          '1 large onion, chopped',
          '1 pound ground beef',
          '½ pound ground pork',
          '1 ½ cups cooked rice',
          '1 teaspoon finely chopped garlic',
          '1 teaspoon salt, plus more to taste',
          '¼ teaspoon ground black pepper, plus more to taste',
          '3 (10.75 ounce) cans condensed tomato soup',
          '2 (12 fluid ounce) cans tomato juice, or more to taste',
          '½ cup ketchup',
        ],
      },
    ],
  },
  {
    id: 3,
    name: 'Bigos',
    description:
      'Cucumbers only pickled for a few days have a different, less sour taste than those pickled for longer. They’re known as ogórek małosolny, which literally means ‘low-salt cucumber’. There is also kiszona kapusta, literally sauerkraut, which might appear strange, due to the method of preparation. Like wine, one has to keep on stepping on it in a barrel…',
    image: 'https://annaeverywhere.com/wp-content/uploads/2019/08/bigos1.jpg',
    steps: [
      'Prep the ingredients: pour hot tap water over the dried mushrooms, grind or crush the juniper berries, cut the pork shoulder into large chunks, cut the sausages into similar-sized chunks, drain the sauerkraut and mushrooms',
      'In a large lidded pot, heat the bacon fat or vegetable oil for a minute or two. Working in batches if necessary, brown the pork shoulder over medium-high heat.',
      'Add the onions and cabbage, then the tomato paste',
      'Add the fresh mushrooms, pork, cabbage, onions and seasonings',
      'Add the beer (or tomato sauce) and simmer',
      'Discard the bones and fat, then add the prunes and cook longer',
      'Add the mustard just before serving',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '1 ounce dried porcini or other wild mushrooms',
          '1 tablespoon black peppercorns',
          '2 pounds pork shoulder',
          '1 to 2 pounds kielbasa or other smoked sausage',
          '1 (25-ounce) jar fresh sauerkraut (we recommend Bubbies, which you may be able to find in the refrigerated section of your local supermarket)',
          '1 1/2 pounds mixed fresh mushrooms',
          '2 tablespoons bacon fat or vegetable oil',
          '1 large onion, chopped',
          '1 green cabbage, cored and chopped',
          'Salt',
          '2 tablespoons tomato paste, optional',
          '1 smoked ham hock',
          '1 pound fresh Polish sausage, optional',
          '1 tablespoon caraway seeds',
          '2 tablespoons dried marjoram',
          '1 to 2 tablespoons mustard or horseradish, optional',
        ],
      },
    ],
  },
  {
    id: 4,
    name: 'Kotlet Schabowy',
    description:
      'Kotlet Schabowy is a pork cutlet in a coating. It’s like Wiener Schnitzel, but thicker. If you ask a Pole to serve you something typically Polish, you’ll be served schabowy with boiled potatoes and warm beets – alternatively with a boiled carrot chopped in cubes mixed with peas. ',
    image: 'https://annaeverywhere.com/wp-content/uploads/2019/08/schabowy.jpg',
    steps: [
      'Place pork chops between 2 sheets of heavy plastic on a solid, level surface. Firmly pound with the smooth side of a meat mallet, turning occasionally, until very thin. Season with salt and pepper.',
      'Pour flour onto a large plate. Whisk egg in a wide, shallow bowl. Place breadcrumbs in a separate shallow bowl.',
      'Dredge chops with flour. Dip in whisked egg. Coat with bread crumbs on both sides. Shake off excess coatin',
      'Heat oil in a large skillet over medium-high heat. Add breaded chops; cook until golden brown, about 5 minutes per side.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '2 boneless pork chops',
          'salt and freshly ground black pepper to taste',
          '1 tablespoon all-purpose flour',
          '1 egg',
          '5 tablespoons bread crumbs',
          '2 tablespoons vegetable oil, or as needed',
        ],
      },
    ],
  },
  {
    id: 5,
    name: 'Kotlet Mielony',
    description:
      'Similar to the Danish meatballs, the Kotlet Mielony is a flat, pan-fried meatball but in a coating. They’re usually eaten with boiled potatoes, or a cold salad like sauerkraut or pickled/boiled beetroots. ',
    image: 'https://annaeverywhere.com/wp-content/uploads/2019/08/mielone.jpg',
    steps: [
      'Finely chop an onion and fry it for about 5 minutes with a bit of oil (medium heat).',
      'Put the stale bread roll in the milk and wait until it soaks.',
      'Place all the ingredients in the bowl and mix them carefully using your hands. If the mixture feels too mushy, add some bread crumbs.',
      'Wash and dry your hands, pour oil on the pan and turn on the heat.',
      'Take a deep plate or a small bowl, and add bread crumbs to it.',
      'Start forming the small cutlets with wet hands.',
      'Coat each cutlet with the bread crumbs',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '1 pound of ground pork',
          '1 egg',
          '1 hard roll (stale bread)',
          '1 cup of milk',
          '1 big onion',
          '2 minced garlic cloves',
          'salt, pepper',
          'bread crumbs',
          'oil to fry',
        ],
      },
    ],
  },
  {
    id: 6,
    name: 'Polish Pork Gulasz',
    description:
      'The gulasz in Poland is the local version of the well-known Goulash dish, of which many Central European countries have their own recipes. The main ingredients are usually tender pieces of beef and then a broth of bell pepper, carrots, mushroom, onions and paprika.',
    image:
      'https://annaeverywhere.com/wp-content/uploads/2019/08/goulash-3773134_1280.jpg',
    steps: [
      'Dredge pork in flour that has been generously seasoned with salt and pepper.',
      'In a large saucepan, brown pork cubes in hot oil. (I did 2 or 3 separate batches.)',
      'Remove pork and brown onions and peppers, add garlic just before they’re finished. (After multiple batches of meat and then the veggies, there was a dark brown crust on the bottom of the pan. Don’t worry, it will loosen and dissolve in the liquids you’re about to add – giving you a dark, flavorful broth.)',
      'Return pork to the pan and add broth, tomato paste, paprika, pepper, allspice and wine.',
      'Simmer covered 60 to 90 minutes',
      'In a small bowl, blend water and 3 tablespoons flour. Add to meat mixture',
      'Simmer 15 to 30 minutes, stirring occasionally',
      'Serve over potato pancakes',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '2 pounds pork, trimmed and diced',
          '3/4 cup flour',
          'Kosher salt',
          'Black pepper',
          '3 tablespoons olive oil',
          '1 cup chopped onion',
          '2 bell peppers, cut into thin strips (I used red and yellow)',
          '2 cloves garlic, minced',
          '14 ounces broth (I used veal reconstituted bullion cubes)',
          '2 tablespoons tomato paste',
          '2 tablespoons paprika',
          '1/4 teaspoon black pepper',
          '6 whole allspice',
          '1/4 cup dry red wine',
          '1/3 cup cold water',
          '3 tablespoons flour',
          'Potato pancakes, cooked according to directions',
        ],
      },
    ],
  },
  {
    id: 7,
    name: 'Kluski Slaskie',
    description:
      'Known in English as Silesian dumplings, these are a simple recipe of eggs, mashed boiled potatoes and flour that are usually eaten with fried beef roulades and rich gravy with some boiled red cabbage.',
    image: 'https://annaeverywhere.com/wp-content/uploads/2019/08/slaskie.jpg',
    steps: [
      'Cook the potatoes in boiling salted water, until tender',
      'Drain thoroughly and mash or rice',
      'Press the mashed potatoes into a bowl and smooth the top',
      'Draw two lines on the top of the potatoes, dividing the mass into fourths',
      'Scoop out 1/4 of the potatoes and fill this space with potato starch, return the potatoes you just scooped out',
      'Add egg and salt, stir until well combined',
      'Roll a small amount of the mixture, about the size of a golf ball, in your hands until smooth',
      'Make an indentation with your thumb and continue smoothing the dumpling',
      'Preparing a large pot of barely simmering salted water',
      'Without overcrowding the pot, place dumplings in water with a slotted spoon',
      'They will rise to the top after a few minutes, if a stubborn one or two stay on the bottom, give them a gentle nudge, they may be stuck',
      'Cook for 5 more minutes, remove with a slotted spoon',
      'Top with with whatever wonderful creation you’re using',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '2 large russet potatoes, peeled and diced',
          'potato starch (1/4 volume of potatoes, see instructions)',
          '1 egg',
          '1/2 teaspoon salt',
        ],
      },
    ],
  },
  {
    id: 8,
    name: 'Pyzy & Knedle',
    description:
      '‘Pyzy’ is a type of large oval-shaped dumpling (the singular being ‘pyza’) stuffed with meat, twarog cheese or mushroom stuffing and boiled in water. They’re so big that they’re usually only served two or three in a portion as a main course.',
    image:
      'https://annaeverywhere.com/wp-content/uploads/2019/08/polish-dishes.jpg',
    steps: [
      'Gather the ingredients.',
      'Cube half the potatoes. Leave the other half of the potatoes peeled but whole.',
      'Cooked the cubed potatoes in boiling, salted water until tender.',
      'Drain and mash or grind through a food mill and place in a large bowl.',
      'Meanwhile, grate the whole potatoes by hand or in a food processor using a very fine grater (you do not want shreds).',
      'Drain grated potatoes and place them in a linen towel or several layers of cheesecloth and twist and squeeze the cloth over a bowl to drain all the water out of the potatoes. Save the potato starch that settles to the bottom of the bowl (but not the water).',
      'Place the potato starch and squeezed-out potatoes in the bowl with the cooked, mashed potatoes.',
      'Add eggs, salt, and both flours, and mix thoroughly, adding enough flour so ​​the mixture will hold its shape when rolled.',
      'Using slightly dampened or floured hands, roll spoonfuls of the dough into balls.',
      'Bring a large saucepan of salted water to a boil and drop in the dumplings. Cook 4 to 5 minutes or until dumplings float to the top. Taste test for doneness. Remove dumplings with a slotted spoon to a colander to drain.',
      'Meanwhile, fry the slab bacon or sliced bacon until golden brown.',
      'Transfer the cooked dumplings to a serving plate and spoon over the bacon and drippings.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '2 1/2 pounds russet potatoes, peeled, divided',
          '2 large eggs, beaten',
          '1/2 teaspoon kosher salt, or to taste',
          '4 ounces all-purpose flour, more as necessary',
          '1 tablespoon potato flour',
          '5 ounces Polish boczek, or sliced bacon, cut into cubes, for garnish',
        ],
      },
    ],
  },
  {
    id: 9,
    name: 'Lazy Pierogi',
    description:
      'The lazy man’s pierogi is a simpler substitute for the very popular Pierogi mentioned above which is what makes it different from the normal recipe. The dough is made by incorporating dry curd cheese such as farmer’s cheese or ricotta and when it’s rolled out into the dumplings, it’s left unfilled. The Lazy Pierogi is usually served as a side dish with sour cream or crispy golden bacon bits.  ',
    image: 'https://kolorowegarnki.pl/wp-content/uploads/2021/04/1-1.jpg',
    steps: [
      'In the bowl of a food processor, whiz together cheese, eggs, egg yolk, salt, and butter until smooth.',
      'Add flour all at once and process.The dough will be sticky and never form a ball.',
      'Put a large pot of salted water on to boil.Remove dough to a floured surface.Form into a 1 1 / 2 - inch - thick rope.Cut diagonally into 1 - or 2 - inch pieces, depending on how large you like them.',
      'Drop dumplings into boiling water.Once dumplings have risen to the top, boil an additional 5 minutes, for a total of about 10 minutes.Remove one dumpling to a plate and cut it into it to taste to make sure it is done to your liking.Be careful because it will be very hot.',
      'With a slotted spoon, remove dumplings to a buttered bowl.They can be served immediately as is topped with sour cream, or fried in butter until golden.Try them with pan drippings from a pork or beef roast.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '1 pound dry curd cheese, farmers cheese, or ricotta cheese, at room temperature',
          '2 large eggs, room temperature',
          '1 large egg yolk, room temperature',
          '1 teaspoon salt',
          '1 tablespoon unsalted butter, melted',
          '2 cups all-purpose flour',
        ],
      },
    ],
  },
  {
    id: 10,
    name: 'Potato Pancakes',
    description:
      'The authentic Polish potato pancakes are a traditional comfort food eaten all over the country. Everyone has their own family recipe but the base is always potatoes, grated onions, eggs and flour, flattened and fried into savory pancakes. ',
    image:
      'https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_4:3/k%2FPhoto%2FRecipes%2F2019-11-recipe-leftover-mashed-potato-pancakes%2F2019-10-21_Kitchn88899_Thanksgiving-Leftover-Pancakes',
    steps: [
      'Gather the ingredients.',
      'Add the potatoes, onion, eggs, 2 teaspoons salt, and pepper to a large bowl.',
      'Add enough flour to bind the mixture together while leaving it somewhat thin.',
      'In a large skillet set over medium-high heat, add vegetable oil to a depth of about 1/4-inch. Heat until hot, but not smoking.',
      'Drop a 1/4 cup of potato mixture into the skillet and spread out to form a 3-inch circle that is about 1/4-inch thick.',
      'Fry until brown on the bottom (don not turn until the pancake is brown or it will stick), about 3 to 5 minutes. If needed, reduce the heat to medium to prevent burning.',
      'Turn the pancake and fry the other side for 3 to 5 minutes or until golden brown and crisp.',
      'Drain on paper towels. Serve with granulated sugar, sour cream and applesauce if desired.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '6 medium potatoes, peeled and finely grated (about 2 1/4 pounds total)',
          '1 medium onion, finely grated',
          '2 large eggs',
          'Kosher salt, to taste',
          'Freshly ground black pepper, to taste',
          '1/4 cup all-purpose flour, more as needed',
          'Vegetable oil, for frying',
          'Granulated sugar, for garnish',
          'Sour cream, for garnish',
          'Applesauce, for garnish',
        ],
      },
    ],
  },
  {
    id: 11,
    name: 'Pork Hock',
    description:
      'Pork hocks, or ham hocks or ‘knuckles’ are actually the ankles of the pig, and when made the traditional way are fork-tender and literally fall off the bone. A lot of places smoke the hock these days but that is not the real Polish way. It’s served with roasted vegetables, boiled potatoes and of course, some sauerkraut.',
    image:
      'https://www.polonist.com/wp-content/uploads/2020/08/Ham-Hock-HenyBeer-1200x1200-1.jpg',
    steps: [
      'Cover the pork knuckles with cold water, add allspice berries, dried marjoram, and bay leaves. Cook slowly for about 3-5 hours until pork knuckles are soft.',
      'In the meantime, peel the carrot, celery root, and onions.',
      'Grate the carrot and celery root. Cut onions into half moons.',
      'Mix the veggies with salt, pepper, and oil.',
      'Take off the cooked pork knuckles from the water. Don not pour out the broth! It is a perfect base for any Polish soup, such as krupnik, white bortsch, or Polish sorrel soup.',
      'Preheat the oven to 356°F (180°C).',
      'Place pork knuckles into the heat-resistant vessel. Add veggies and beer.',
      'Bake in the oven for about 1 hour.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '6-7 pork knuckles',
          '3 carrots',
          '1 celery root',
          '2 onions',
          '7 allspice berries',
          '5 bay leaves',
          '1 tbsp of dried marjoram',
          '1 tbsp of salt',
          '1 tsp of black pepper',
          '2 tbsps of oil',
          '2 cups of beer',
        ],
      },
    ],
  },
  {
    id: 12,
    name: 'Zrazy',
    description:
      'This dish actually dates back to the 14th century and used to be served to the nobility. Today it’s not too restricted and is a very common main course in most places. Zrazy (pronounced ZRRAH-ZIY) is essentially meat, usually beef, roulade that’s cooked for several hours in a slow cooker and served with potatoes and the popular side dish of red cabbage.',
    image: 'https://annaeverywhere.com/wp-content/uploads/2019/08/zrazy.jpg',
    steps: [
      'Spread a thin layer of mustard on each steak and divide the pickles, ham, and onion among the steaks. Fold in the sides and roll like stuffed cabbage. Secure with a toothpick, if necessary.',
      'Heat oil in a large Dutch oven and brown beef rolls on all sides. Remove meat and reserve.',
      'Add flour to the pan and cook until light brown to make a roux. Stir in the stock, wine, tomato paste, salt, and pepper. Bring to a boil and simmer 1 minute.',
      'Return beef rolls to the pan and spoon over some of the sauce. Cover and cook on low 45 minutes to 1 hour, adding more liquid as necessary during cooking.',
      'When the rolls are cooked, transfer to a serving dish and remove the toothpicks, if used, and ladle over the sauce. Dollop with sour cream and chopped parsley.',
      'Serve with rice, mashed potatoes, finger dumplings, or drop potato dumplings.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '8 sandwich steaks',
          '1 tablespoon grainy mustard, or to taste',
          '2 dill pickles, cut into thin strips',
          '4 ounces ham, cut into thin strips',
          '2 green onions, white and light green parts, cut into thin strips',
          '4 tablespoons canola oil',
          '2 tablespoons all-purpose flour',
          '1 cup beef stock',
          '4 tablespoons white wine',
          '1 tablespoon tomato paste',
          '1 teaspoon salt, or to taste',
          '1/2 teaspoon freshly ground black pepper, or to taste',
          'Sour cream, for garnish',
          'Chopped parsley, for garnish',
        ],
      },
    ],
  },
  {
    id: 13,
    name: 'Ryba po Grecku',
    description:
      'Literally translated, this dish means Greek-style fish, so it’s quite obvious that the Polish borrowed this cooking style from the Greeks. The main course meal is fried fish fillets in a sauce made from a tomato base and can be served hot and cold.  ',
    image:
      'https://www.polonist.com/wp-content/uploads/2020/12/christmas-fish-ryba-po-grecku-1200sq-720x720.jpg',
    steps: [
      'Wash fish fillets, pat dry and cut into about 3-4 inch / 8-10 centimeter pieces. Sprinkle with salt and pepper.',
      'Break an egg into one dish, add a tablespoon of water and scramble. Place flour in another dish. Heat oil in a non-stick frying pan. Dip each piece of fish in egg, then flour and sauté on medium until cooked and lightly golden brown. Remove and place on a paper towel.',
      'Peel carrots, parsnip, and celery root and grate on the largest side of a vegetable box grater. Chop onion. Heat oil and butter in a wide pan / deep frying pan and add peppercorns, allspice berries, and bay leaves, followed by shredded vegetables and onions. Heat through. Add broth, tomato paste, salt and pepper, and paprika. Sauté until cooked, about 5-7 minutes. Do not overcook, leave a bit of crunch in the veggies.',
      'Taste. Add a bit more salt, if needed.',
      'Once veggies are cooked, create layers in a serving dish by placing about ⅓ of the veggie mixture first, then arrange fish pieces and cover with the rest of the veggie mixture. Cover with foil and let cool.',
      'Refrigerate until serving.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '1 lb / 500 g of fish filets (any white, mild fish will do)',
          '1 egg',
          '3 tbsp of all-purpose flour',
          '3-4 tbsp of oil',
          '5 carrots',
          '1 parsnip',
          '½ a medium celery root or ¾ of a small one',
          '1 ½ c of chopped onion',
          '1 tbsp of oil + 1 tbsp of butter',
          '6 whole peppercorns and allspice berries (each)',
          '3 bay leaves',
          '½ c / 110 ml of vegetable broth or water',
          '3 tbsp of tomato paste',
          '1 tsp salt',
          'Sprinkle of pepper',
          '2 tsp paprika',
        ],
      },
    ],
  },
  {
    id: 14,
    name: 'Fasolka po Bretońsku',
    description:
      'Fasolka po bretonsku is the Polish version of homemade baked beans. It’s made from Harico beans in a thick rich stew usually served with some fresh warm bread.',
    image:
      'https://eatingeuropean.com/wp-content/uploads/2018/01/Breton-Beans-Fasolka-Po-Bretonsku-1.jpg',
    steps: [
      'Add beans to a bowl and cover with lots of water and soak overnight.',
      'Rinse the beans and add them to the pot with 6 cups of water. Bring to boil, cover and cook for about an hour to an hour and a half. The cooking time depends on beans. They should be soft but not overcooked;',
      'In a frying pan heat up one tablespoon of butter or ghee or cooking oil and add cubed kielbasa (sausage) and cook until golden brown for about 5 minutes;',
      'Once the sausage is cooked remove from the pan and set aside; ',
      'Add onions to the same pan; if needed add extra fat; cook until golden and soft, for about 3-4 minutes; add garlic and cook for another minute.',
      'Once the beans are cooked add sausage and onions/garlic mixture to the pot with the beans;',
      'Add bay leaf, allspice, crushed tomatoes, tomato paste, marjoram, half a teaspoon of salt and freshly ground pepper and cook for about 15 minutes;',
      'Check for seasoning, add more salt and pepper if needed; optionally add pinch of cayenne for some heat; sprinkle with fresh parsley and serve with crusty bread.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '1 cup Beans Dried',
          '1 Onion medium, sweet, chopped',
          '2 cloves Garlic chopped',
          '1 cup Kielbasa Smoked Polish Sausage, cubed',
          '2 cups Crushed Tomatoes',
          '1 tbsp Tomato Paste',
          '3 teaspoon Marjoram',
          '1 Bay Leaf',
          '3 Allspice',
          '6 cups Water',
          'Salt & Pepper to taste',
          'Pinch Cayenne Pepper optional',
          '1 tbsp butter ghee or cooking oil',
          '1 teaspoon Parsley chopped',
        ],
      },
    ],
  },
  {
    id: 15,
    name: 'Rice with Apples',
    description:
      'This may sound a bit like an odd mixture but this pudding is actually a delicious autumnal dessert baked with cinnamon and sugar. It’s served with a side of whipped sour cream with some sugar. ',
    image:
      'https://cdn.aniagotuje.com/pictures/articles/2020/09/8007867-v-1500x1500.jpg',
    steps: [
      'Preheat the oven to 350° F (180° C).',
      'Bring the milk and water to a boil. Reduce the heat to low and add the rice, 1 tablespoon butter, and a pinch of salt. Simmer uncovered, stirring occasionally until the liquid is absorbed. Remove from the heat. Stir in the vanilla and 1/4 cup sugar. Cover and set aside.',
      'Peel, core, and slice the apples into 1/4 inch slices. Now slice across the apple slices making 1/4 inch pieces. Toss the diced apples with 2 teaspoons cinnamon and 2 teaspoons sugar.',
      'Grease a medium casserole dish. Add 1/3 of the rice to the bottom of the dish. Top with half of the apples. Add another layer of rice, top with apples, and the final 1/3 of the rice is the top layer. Pour the heavy cream over the top of the layers and top with 3 tablespoons of thinly sliced butter. Sprinkle lightly with more cinnamon.',
      'Bale 40 – 45 minutes. Serve warm with a dollop of optional sour cream or greek yogurt.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '1 cup milk (250ml)',
          '1 cup water (250ml)',
          '1 cup rice (220g)',
          '1 tablespoon butter',
          'pinch of salt',
          '4 tablespoons sugar',
          '1/2 teaspoon vanilla',
          '1 3/4 pounds apples (800g), about 5',
          '2 teaspoons cinnamon',
          '2 teaspoons sugar',
          '1/2 cup heavy cream, (100g)',
          'sour cream or greek yogurt to serve on the side (optional)',
        ],
      },
    ],
  },
  {
    id: 16,
    name: 'Barszcz z Uszkami',
    description:
      'The word Uszka actually means ‘little ears’ and it’s quite appropriate given the shape of the little mushroom or minced meat dumplings that come in the Barszcz which is a sour soup or borscht that’s colored red by its beetroot base. Get the recipe for red borscht here.',
    image:
      'https://annainthekitchen.com/wp-content/uploads/2021/06/red-borsch.jpg',
    steps: [
      'Gather the ingredients.',
      'Place the beets in a large crock or ceramic bowl.',
      'Cover with pre-boiled lukewarm water. Add the bread with the crust, pushing it under the water.',
      'Cover the crock or bowl with cheesecloth and let stand at room temperature for three days.',
      'Strain through cheesecloth, pour into a glass jar and seal it. Store in the fridge. You may eat the strained beets or discard them.',
      'Place the beets, Polish soup vegetables (włoszczna) in a large stockpot.',
      'Add 6 cups cold water and 1 teaspoon of the butter. Bring to a boil, reduce heat, and simmer until vegetables are tender.',
      'Strain, pressing on vegetables to extract every last ounce of liquid.',
      'Return the strained liquid to the pot and add mashed garlic with a little salt, the beet sour (kwas), strained mushroom soaking liquid, salt, pepper, and sugar to taste.',
      'Bring to a boil, reduce heat, and simmer 30 minutes.',
      'Before serving, stir in the remaining 1 teaspoon of butter and parsley.',
      'Ladle into hot bowls and serve with mushroom uszka.',
    ],
    ingredients: [
      {
        section: 'For the Beet Sour (Kwas)',
        items: [
          '3 1/2 pounds beets, peeled, rinsed, and sliced',
          '1 slice rye bread',
        ],
      },
      {
        section: 'For the Beet Soup',
        items: [
          '1 pound beets, peeled, rinsed, and sliced',
          '1/2 pound vegetables, such as carrot, parsnip, celery root, leeks, peeled and sliced',
          '2 teaspoons unsalted butter',
          '1 clove garlic, mashed with a little salt',
          '2 cups beet sour (kwas)',
          '1 dried mushroom, soaked, 1/4 cup soaking liquid reserved',
          'Salt, to taste',
          'Freshly ground black pepper, to taste',
          '1 teaspoon sugar, or to taste',
          '1 tablespoon finely chopped parsley',
        ],
      },
    ],
  },
  {
    id: 17,
    name: 'Zurek',
    description:
      'This unique and humble soup is popular in many West Slavic states but the Polish version is traditionally eaten around Easter time. It’s known as the Polish Ryemeal Soup and is made by fermenting the cereal (Rye) and cooking it with sausage, bacon or ham. It’s creamy, smokey, cooked with lots of garlic and is not as sour as fermenting suggests, it’s more a rich savory sour taste.',
    image: 'https://annaeverywhere.com/wp-content/uploads/2019/08/zurek.jpg',
    steps: [
      'In a clean glass jar, mix rye flour with warm, purified water.',
      'Cover the jar with a linen cloth or gauze. Place it in the cold (max 20°C / 68°F), dark place',
      'Pour water into a big pot. Add allspice berries and bay leaves and bring to boil.',
      'Reduce the heat. Add smoked pork bones, bacon, and white sausage. Cook for about 30 minutes, but don not bring it to a boil!',
      'In the meantime, peel and dice an onion, then fry it on oil.',
      'Take off the meat. Dice the bacon and cut the white sausage in slices or bigger chunks. You may also remove meat from the bones and dice it.',
      'Stir zakwas for about 1 minute, making sure there are no lumps.',
      'Bring the żurek to boil, reduce the heat, then slowly start pouring zakwas into it, stirring all the time.',
      'Cook for about 5 minutes.',
      'Turn off the heat.',
      'Add crushed garlic cloves, marjoram, and salt.',
    ],
    ingredients: [
      {
        section: 'Starter',
        items: ['5 tbsps of rye flour', '2 cups of purified water'],
      },
      {
        section: 'Main dish',
        items: [
          '35 oz (1kg) of smoked pork bones',
          '10 oz (300g) of bacon',
          '3 quarts / litres of water',
          '5 allspice berries',
          '3 bay leaves',
          '4 white sausages',
          '1 onion',
          '3 garlic cloves',
          '1 tbsp of dried marjoram',
          '2 tbsps of salt',
          '1 tbsp of oil',
        ],
      },
      {
        section: 'Add-ons to choose',
        items: ['2 boiled potatoes', '2 boiled eggs'],
      },
    ],
  },
  {
    id: 18,
    name: 'Pączki ',
    description:
      'These Polish doughnuts are dusted with sugar or bits of dried orange zest and filled with a sweet filling similar to a jelly or jam. These fried rounds of yeast dough are typically stuffed with rose hip, prune, apricot, strawberry, raspberry, or sweet cheese filling. Some people make these puffy doughballs without a filling and roll them in granulated sugar, which is equally delicious. Whichever way you make them, keep in mind that pączki differ from regular doughnuts insofar as these Polish treats are sweeter and richer.',
    image:
      'https://annaeverywhere.com/wp-content/uploads/2019/08/donuts-690281_1280.jpg',
    steps: [
      'Add the yeast to the warm milk. Stir to dissolve and set aside.',
      'In a large bowl or stand mixer fitted with the paddle attachment, cream together the sugar and butter until fluffy.',
      'Beat in the egg, egg yolks, brandy or rum, and salt until well incorporated.',
      'Still using the paddle attachment, add 4 1/2 cups flour, alternating with the milk-yeast mixture. Beat for 5 or more minutes by machine or longer by hand until smooth. (Old-fashioned directions call for beating the dough with a wooden spoon until it blisters.) The dough will be very slack. If it is too soft, add the remaining 1/2 cup flour but no more.',
      'Place the dough in a greased bowl. Turn to grease the other side.',
      'Cover the top with plastic wrap and let rise until doubled in bulk, anywhere from 1 to 2 1/2 hours.',
      'Punch down and let rise again, about 45 minutes.',
      'Turn dough out onto a lightly floured surface. Pat or roll to 1/2-inch thickness. Cut rounds with a 3-inch biscuit cutter close together so you will have minimal scraps. Remove scraps and reroll and recut.',
      'Cover the sheet with a damp towel and let rounds rise until doubled in bulk, 30 minutes or longer, before frying.',
      'In a large skillet or Dutch oven, heat oil to 350 F. Place the risen pączki top-side down (the dry side) in the oil a few at a time and fry 2 to 3 minutes or until the bottom is golden brown.',
      'Flip them over and fry another 1 to 2 minutes or until golden brown. Make sure the oil does not get too hot so the exterior doe not brown before the interior is done. Test a cool one to make sure it is cooked through. Adjust cooking time and oil heat accordingly.',
      'Drain pączki on paper towels or brown paper bags.',
      'Roll in granulated sugar while still warm. If you want to fill them, poke a hole in the side of the pączki and, using a pastry bag, squeeze in a generous dollop of the filling of choice. Then dust the filled pączki with granulated sugar, confectioners, sugar, or an icing glaze.',
      'Pączki do not keep well, so for the best taste, be sure to gobble them up the same day you make them or else freeze them. Enjoy.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '2 packages active dry yeast (4 1/2 teaspoons)',
          '1 1/2 cups milk, warm, about 110 F',
          '1/2 cup granulated sugar',
          '1/2 cup butter, at room temperature',
          '1 large egg, at room temperature',
          '3 large egg yolks, at room temperature',
          '1 tablespoon brandy or rum',
          '1 teaspoon salt',
          '4 1/2 to 5 cups all-purpose flour (about 20 1/4 ounces to 22 1/2 ounces)',
          '1 gallon vegetable oil, for deep-frying',
          'About 1/2 cup granulated sugar, for rolling, optional',
          'About 1/2 cup confectioners sugar, for rolling, optional',
          '1 cup jam or fruit paste, for filling, optional',
        ],
      },
    ],
  },
  {
    id: 19,
    name: 'Faworki – Angel Wings',
    description:
      'These crispy wisps of pastry dusted with powdered sugar have become quite popular all over many European countries but the Polish version definitely has its own unique twist. You’ll see them most during Christmas time or traditionally during Carnival time around Shrove Tuesday.',
    image:
      'https://annaeverywhere.com/wp-content/uploads/2019/08/eating-3082778_1280.jpg',
    steps: [
      'Put all your ingredients (minus oil to fry) in a big bowl, mix together and knead the dough.',
      'Put the dough ball on a dry and clean surface and knead the dough more by flattening it and kneading again.',
      'In order for the faworki dough to be well aired, it should be kneaded several times and even hit with a rolling pin. I recommend doing it for about 15 minutes. If you have a Kitchenaid pasta attachment you can run it through it twice to speed things up.',
      'Split the dough into three pieces and cover two of them in a foil, while you work on the first one by rolling it out as thin as possible on a clean and dry work surface (you can sprinkle it with some flour). The flattened dough needs to be as thin as possible, almost transparent.',
      'Using a knife or knurling, cut the cake into strips no wider than 1" and no longer than 4". Make an incision in the center of each strip through which to pass (thread) one end of the dough.',
      'Cover with a cotton cloth so it does not dry and repeat this step with your other two pieces of dough.',
      'Prepare the oil in a giant frying pan or wide pot and heat it up to around 340 F, not hotter. If you do not have a thermometer you can check it by putting one angel wing on the oil - it should instantly come out to the top.',
      'Fry your angel wings fro about 40 seconds on each side and using kitchen tongs remove from the frying pan and spread them out on paper towels.',
      'Your faworki should have some air bubbles and be crunchy, not bendy. Sprinkle them with powdered sugar.',
    ],
    ingredients: [
      {
        section: 'Main dish',
        items: [
          '2.5 cups of flour',
          '1/2 half of sour cream',
          '4 egg yolks',
          '1 tablespoon of butter',
          '1 tablespoon of powdered sugar',
          '1 teaspoon of vinegar',
          'oil to fry',
          'powdered sugar to sprinkle on top',
        ],
      },
    ],
  },
  {
    id: 20,
    name: 'Makowiec',
    description:
      'This is one of Poland’s most popular sweet foods, the Poppyseed roll (pronounced mah-KOH-vyets) is rolled out sweet yeast bread with a rich bittersweet filling of poppy seed paste.',
    image: 'https://annaeverywhere.com/wp-content/uploads/2019/08/mak127.jpg',
    steps: [
      'Place raisins in hot water (or rum, whiskey or brandy) and set aside to soak.',
      'Warm milk slightly, add yeast and sugar and set aside in a warm spot for 10 min. Melt butter and set aside to cool slightly.',
      'To make dough, place flour in a mixing bowl. Whisk egg with egg yolks and add to flour. Add milk/sugar/yeast mixture and start combining. Add melted butter and work to combine all ingredients. Add a few tablespoons of milk if dough is too dry. Dough should have consistency of play-dough - not sticky but playable. Once a dough ball is formed, cover and set aside in a warm place for at least 1 hour.',
      'To make filling, place poppyseeds in a pot, add boiling water and soak for 10 min, then boil for 20-25 min. Add a bit more water if they get dry, enough to cover. Drain well. Once it cools slightly you will have to put it through a meat grinder with the fine grinding plate - TWICE.',
      'In a large skillet or a pot heat butter, add poppyseeds, sugar, honey, drained raisins and mix well. Heat through and mix until sugar is dissolved. Add crushed walnuts and mix. Set aside to cool. Whip egg whites with a pinch of salt until stiff. Add to poppyseed mixture and fold in gently.',
      'Once the dough rises, divide in half. Roll out each half into a rectangular shape (30 cm x 25 cm / 12 in x 9 in). Place rolled out dough onto parchment paper large enough to go around your roll twice. Place half of the filling on the first rectangle leaving a bit of space on each side(** see pictures below). Roll starting from the shorter side, pinch the ends together as you go along. Wet the edge with water or egg white for better seal.',
      'Once rolled, make sure to leave on parchment paper with the long seam down. Roll parchment paper around the poppyseed roll twice, leaving space for roll to "grow" (about 3/4 inch / 2 cm). Make sure the end of the paper is under the roll. Set aside in a warm place to rise for about 30-45 min.',
      'Do the same with the second roll.',
      'When ready to bake, heat oven to 350°F / 180°C. Place in hot oven and bake for 40-50 min. Remove and cool.',
      'To make glaze, mix powdered sugar with lemon juice. Add hot water teaspoon at a time and whisk to combine. It should make a thick paste. If it comes out too watery, add more powdered sugar. Spoon onto each roll. Sprinkle with orange peel or almond shavings. Let set.',
    ],
    ingredients: [
      {
        section: 'Filling',
        items: [
          'About 17 oz / 500 g of raw black or blue poppyseeds*',
          '3 cups / 750 ml of boiling water',
          '4 oz / 100 g of butter',
          '1 cup / 250 g of sugar',
          '4 tbs of honey',
          '3/4 cup / 100 g raisins',
          '1 cup / 100 g walnuts',
        ],
      },
      {
        section: 'Dough',
        items: [
          '3/4 cup / 150 ml of warm milk',
          '1/2 cup / 110 g of sugar',
          '1 1/2 tbs of dry active yeast',
          '3 1/2 cups / 500 g of all purpose flour',
          '1 egg plus 2 yolks (large eggs)',
          '2 oz / 50 g of butter',
          'Pinch of salt',
        ],
      },
      {
        section: 'For glaze',
        items: [
          '5 tbs / 55 of powdered sugar',
          '2 tbs of lemon juice',
          '1 tbs of hot water',
          '3-5 tbs of orange peel or sliced almonds',
        ],
      },
    ],
  },
];
